### ISSUE TITLE
Published site?

### ISSUE THREAD

**Issue by srid** [inariksit/cclaw-zettelkasten#1]
Hey folks, just a question about your site. 

Do you deploy the published site to GitHub Pages? Because https://inariksit.github.io/cclaw-zettelkasten/ gives 404, despite your Actions yml using a github-pages workflow. I ask because I'm in the middle of documenting how to use GitHub Actions and GitHub Pages to setup "automatic publish" of neuron sites, and would be interested in gathering examples for the documentation.

**Comment by anka-213** [comment]
@srid Yes, I was trying to do that, but I am not sure why it doesn't work. It does however work on my test-setup: https://anka-213.github.io/test-gh-actions-neuron/
It might have something to do with the contents of the base-page https://github.com/inariksit/inariksit.github.io? Or some other setting I don't know about.

**Comment by srid** [comment]
I have the same problem. It works for https://github.com/srid/neuron-template - but not for https://github.com/srid/neuron-test

I've contacted GitHub support asking them what the problem is.

**Comment by srid** [comment]
Okay @Eyebrowhairs found a workaround for this issue. 

1. Go to repository settings
1. Under 'GitHub Pages' change the branch to something else (say `master`)
1. Then change it back to what it was (usually `gh-pages`)
1. Make a commit if necessary

Now the site should appear in the target URL. 

FWIW, I use the [deploy-to-github-pages](https://github.com/marketplace/actions/deploy-to-github-pages) action, but I'd be curious to know if the same workaround will resolve the issue on this repository (which uses `peaceiris/actions-gh-pages@v3` action) as well.

**Comment by srid** [comment]
Looks like it works: https://inariksit.github.io/cclaw-zettelkasten/ 

I assumed you did that workaround?

**Comment by anka-213** [comment]
Yep. The workaround worked. Thanks!
