### ISSUE TITLE
Wiki link migration script

### ISSUE THREAD

**Issue by srid** [inariksit/cclaw-zettelkasten#2]
You folks may want to migrate from `<..>` to the new wiki-links (`[[[...]]]` and `[[..]]`). Here's a script that will help with that:

https://github.com/srid/neuron/issues/449#issuecomment-719062302

Neuron is dropping support for the former syntax. 

I just ran this script (with manual changes) on my own notes: https://github.com/srid/srid.ca/commit/798aa25a2338126e730c467db8108d3c5f65e186

**Comment by anka-213** [comment]
Thanks!

**Comment by inariksit** [comment]
Thanks for the reminder! I just wasn't using this for a long time so I didn't care migrating it.

**Comment by inariksit** [comment]
Fixed by 05d7f67

**Comment by srid** [comment]
Just a note: `[[...]]#` is the same as `[[[...]]]`, and the former is supported on apps like Obsidian (but the later is not).

https://neuron.zettel.page/folgezettel
